services:
  fisherman:
    build: .
    container_name: fisherman-bot
    user: "${FIX_UID:-1000}:${FIX_GID:-1000}"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///app/data/fisherman.db
      - RUST_LOG=info
      - REDIRECT_URI=https://fisherman-cli.monsieurcotcot.com/auth/callback
