use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Serialize, Deserialize, Clone, Copy, PartialEq, Eq, Hash)]
#[serde(rename_all = "lowercase")]
pub enum Rarity {
    Common,
    Uncommon,
    Rare,
    VeryRare,
    Epic,
    Legendary,
    Mythical,
}

impl Rarity {
    pub fn odds() -> Vec<(Rarity, f64)> {
        vec![
            (Rarity::Common, 60.0),
            (Rarity::Uncommon, 18.0),
            (Rarity::Rare, 10.0),
            (Rarity::VeryRare, 6.0),
            (Rarity::Epic, 3.5),
            (Rarity::Legendary, 1.5),
            (Rarity::Mythical, 0.5),
        ]
    }
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct FishData {
    pub name: String,
    pub size_min: f64,
    pub size_mean: f64,
    pub size_sigma: f64,
    pub force_pristine: Option<bool>,
    pub descriptions: HashMap<String, Vec<String>>,
}

pub fn get_fail_attempt_reasons() -> Vec<&'static str> {
    vec![
        "🎣 Pas de chance @#viewer_name#. Le poisson a mordu, mais il s'est échappé au dernier moment.",
        "🎣 Pas de chance @#viewer_name#. Le poisson a mordu, mais il s'est échappé au premier moment.",
        "🎣 Pas de chance @#viewer_name#. Le poisson a mordu et fuit avec votre apât.",
        "🪨 Pas de chance @#viewer_name#. L'hameçon s'est accroché à des racines sous l'eau.",
        "🌬️ Le vent a rendu la pêche difficile pour @#viewer_name# aujourd'hui. Vous n'arrivez pas à pecher un seul poisson.",
        "🕳️ Aucune prise pour @#viewer_name#, il semblerait que les poissons ne soient pas dans les parages.",
        "🎣 La ligne s'est emmêlée et a dû être remontée sans rien. Dommage @#viewer_name#.",
        "🔊 Le bruit autour de vous a effrayé les poissons.",
        "🪱 L'appât n'a pas attiré les poissons cette fois-ci. Dommage !",
        "🤦 La canne vous a glissé des mains, vous râtez une belle prise. Mince :/",
        "🌊 Le courant était trop fort cette fois-ci pour garder votre ligne stable. Vous ne remontez pas de poisson.",
        "🐟 Un poisson énorme a cassé la ligne et s'est enfui !!! Oh le coquin !!",
        "🪝 L'hameçon était mal positionné, rien n'a pu mordre.",
        "🦅 Un oiseau est passé par là et a effrayé les poissons.",
        "🐠 Les poissons semblaient méfiants et ne se sont pas approchés.",
        "🪴 Une algue vous empeche de remonter l'hameçon.. Vous n'arrivez plus à pêcher.",
        "🔗 Le fil s'est rompu pendant que vous tiriez.",
        "⌛ Vous avez attendu trop longtemps avant de remonter la ligne. Pas de poissons.",
        "☀️ Le soleil était trop fort, et les poissons se cachaient au fond de l'eau.",
        "🦀 Un crabe a volé votre appât avant qu'un poisson ne puisse mordre 😂 Oh le coquin !!",
        "😅 Votre patience a payé... mais avec une ligne vide.",
        "🎣 Un petit coup de malchance, vous ne remontez rien. Peut-être demain !",
        "🚫 Les poissons étaient là, mais ils ont décidé de faire grève aujourd'hui.",
        "🍤 L'appât était trop petit pour attirer un poisson.",
        "🐡 Un poisson-globe a gonflé et a fait fuir tous les autres poissons.",
        "🧵 Le nœud de votre ligne était mal fait et s'est défait. Pas de poisson pour cette fois.",
        "⛵ Une embarcation a fait des vagues et a perturbé votre zone de pêche. Les poissons ont déguerpi !",
        "🐬 Un dauphin curieux a effrayé les poissons en s'approchant de vous.",
        "🎆 Un bruit soudain, peut-être un feu d'artifice, a fait fuir tous les poissons. Rohhh...",
        "❄️ L'eau était trop froide aujourd'hui, les poissons ne mordent pas à l'hameçon.",
        "⚡ Un orage soudain a perturbé votre tentative de pêche.",
        "🌑 La lumière était insuffisante pour que les poissons remarquent votre appât.",
        "🩹 Une blessure sur votre main vous a fait rater la prise.",
        "🐊 Un crocodile roux a fait fuir les poissons. Ok.",
        "🐊 Un vieux crocodile a fait fuir les poissons. Hmmm.",
        "🐊 Un gros crocodile a fait fuir les poissons. Vous avez de la chance qu'il ne vous ait pas bouffé.",
        "🐊 Un petit crocodile a fait fuir les poissons. Petit mais déjà effrayant !",
        "🐊 Une madame crocodile a fait fuir les poissons. Elle n'a pas l'air de déconner.",
        "🕶️ Vous ne pouviez pas bien voir à cause de la lumière reflétée sur l'eau.",
        "🧼 Votre appât sentait trop fort, les poissons l'ont évité.",
        "🚫 Le panneau disait 'Pêche interdite', et vous n'avez rien osé attraper.",
        "💩 Une pollution dans l'eau a éloigné toute vie marine.",
        "🍵 Vous vous êtes endormi en attendant une prise et avez raté l'action. Mince !",
        "🎭 Les poissons jouent à cache-cache et semblent s'amuser sans vous 😋 !",
        "👻 Une légende raconte que cette zone est hantée, les poissons évitent l'endroit.",
        "🧲 Un aimant mal placé a attiré votre hameçon, sans poisson au bout.",
        "🕸️ Un vieux filet abandonné a empêché votre ligne d'avancer.",
        "🐕 Un chien a attrapé votre appât avant qu'il ne touche l'eau. Pauvre chien 😣 !",
        "🪓 Une branche tombée dans l'eau a fait fuir tous les poissons. Roohh...",
        "🍌 Vous avez glissé sur une peau de banane et raté votre chance !! Une peau de banane dans l'eau ??",
        "🍌 Une rumeur dit que la ✨Banane Pristine✨ pourrait se trouver ici... mais pas aujourd'hui. Vous ne remontez rien du tout.",
        "🍌 Vous avez confondu une peau de banane flottante avec un poisson… quel échec...",
        "🍌 Une légende raconte que quiconque trouve la ✨Banane Pristine✨ n'aura plus jamais de chance en pêche. Peut-être que c'est une bénédiction ?",
        "📮 Vous avez vu une ✨Carte Postale✨ flotter à la surface... mais elle a coulé avant que vous ne puissiez l'attraper. Rolf.",
        "📮 Un viel homme vous parle de la légende de la ✨Carte Postale✨ signée 'MonsieurCotCot'. Elle serait ici, sous l'eau.",
        "📮 Un oiseau a traversé votre ligne et l'a cassée... Pas de chance.",
        "🍃 Une feuille s'est prise à votre hameçon, pas vraiment appétissant pour un poisson. Vous ne remontez pas de poissons.",
        "📜 Vous avez cru pêcher un poisson rare, mais c'était juste un vieux morceau de papier.",
        "🍌 Une banane mystérieuse a attiré tous les poissons loin de vous... ",
        "🌊 Une vague soudaine a emporté votre hameçon, laissant votre ligne vide.",
        "🕳️ Les poissons se sont réfugiés dans des profondeurs où vous ne pouvez pas les atteindre...",
        "👻 Une ombre étrange sous l'eau a effrayé les poissons... peut-être un fantôme marin ? Ou juste un poisson avec un drap blanc 🤷 ?",
        "💌 Une ✨Carte Postale✨ s'est envolée au moment où vous alliez la saisir... Dommage.",
        "🍌 Votre appât s'est coincé dans un amas de bananes pourries sous l'eau... étrange, non ?",
        "🪝 Un poisson curieux a mordu... puis a laissé tomber en rigolant (on aurait dit un rire !).",
        "📜 Vous pensiez avoir trouvé un trésor, mais c'était juste un ticket de parking détrempé.",
        "🍌 Une rumeur dit que la ✨Banane Pristine✨ ne peut être trouvée que par les élus. Pas vous, aujourd'hui !",
        "📮 Un poisson a attrapé la ✨Carte Postale✨ et l'a gardée pour lui. Malin 😂 !",
        "🪝 Votre hameçon a attrapé quelque chose... mais c'était un vieux filet.",
        "🍌 Une banane flottante a distrait les poissons et vous les avez ratés.",
        "📮 Une ✨Carte Postale✨ est apparue à la surface... mais elle était hors de portée.",
        "🌧️ Une pluie torrentielle a rendu la pêche impossible, les poissons restent cachés.",
        "🌩️ Un éclair a effrayé tous les poissons de la zone... et vous aussi !",
        "☀️ Le soleil tape si fort que même les poissons sont allés se cacher à l'ombre.",
        "🌊 Une énorme vague a emporté votre appât au loin, sans espoir de le récupérer.",
        "🌬️ Une rafale de vent a fait s'emmêler votre ligne. Plus de pêche pour l'instant.",
        "🌈 Un arc-en-ciel est apparu, vous en oubliez les poissons qui ont pris l'apat.",
        "🌨️ La neige a recouvert la surface de l'eau, rendant la pêche impossible.",
        "💨 Une tempête approche et les poissons semblent fuir la zone.",
        "🌫️ Le brouillard est si épais que vous avez lancé votre ligne sur la rive opposée.",
        "🌪️ Une mini-tornade sur l'eau a fait fuir tout ce qui était vivant.",
        "❄️ L'eau glacée a figé votre ligne... et les poissons sont restés immobiles.",
        "☔ Votre parapluie s'est retourné et vous n'avez pas pu vous concentrer sur votre ligne.",
        "⛈️ Une averse soudaine a ruiné votre tentative de pêche.",
        "🌅 Le coucher de soleil était magnifique, mais les poissons n'étaient pas au rendez-vous.",
        "🌄 Le lever du soleil était prometteur, mais les poissons dormaient encore.",
        "🔥 La chaleur a asséché l'étang... plus d'eau, plus de poissons.",
        "💧 Une goutte d'eau sur votre nez vous a fait éternuer et effrayer les poissons.",
        "⚡ Un bruit de tonnerre lointain a fait fuir les poissons avant qu'ils ne mordent.",
        "🌾 Le vent a emporté des brindilles dans votre ligne, les poissons ont perdu tout intérêt.",
        "🍂 Les feuilles tombées dans l'eau ont rendu l'appât invisible.",
        "🎐 Le vent a soufflé si fort qu'il a emporté votre chapeau... et votre chance.",
        "🌤️ Une brise agréable... pour vous, mais pas assez pour attirer les poissons.",
        "❓ Un phénomène météo étrange a fait disparaître les poissons, comme par magie. Bizarre.",
        "💨 Vous avez lancé votre ligne en direction d'un petit coin d'eau, mais une rafale de vent a dévié sa trajectoire dans les roseaux.",
        "🌞 Les poissons bronzaient au fond de l'eau, totalement désintéressés. Dommage.",
        "🌧️ Les gouttes de pluie ont brouillé votre vision et vous avez manqué la touche. Le poisson est reparti...",
        "🌪️ Une bourrasque a fait tourner votre ligne comme une toupie, échec assuré pour pecher aujourd'hui.",
        "💦 Une courte averse vous a surpris et vous en avez lâché votre canne dans l'eau !",
        "🌟 Une étoile filante a distrait tout le monde, y compris vous et les poissons. Pas de poissons mais un beau spectacle !",
        "🍃 Votre hameçon s'est accroché à tout un tas de feuilles mortes qui flottent sur l'eau...",
        "🌀 Une onde étrange a créé des tourbillons, piégeant les poissons loin de votre ligne... Arf...",
        "❄️ Une fine couche de glace s'est formée juste au moment où vous alliez lancer. Impossible de pêcher...",
        "🌊 Une marée subite a déplacé les poissons vers une autre zone de pêche. Rien à remonter pour cette fois...",
        "🎣😞 Oh non ! La ligne de @#viewer_name# s'est emmêlée autour d'un rocher, l'empêchant de continuer à pêcher.",
        "🐧 Soudain, @#viewer_name# aperçoit un groupe de pingouins joueurs qui effraient tous les poissons.",
        "🎮😮 Juste au moment où @#viewer_name# allait remonter une grosse prise, la rage de Mike après une défaite à League of Legends a envoyé des vibrations dans l'eau, effrayant les poissons !",
        "🎣📦 Incroyable ! @#viewer_name# vient de remonter une boîte en bois scellée. Quels mystères pourrait-elle contenir ? Hmm, rien :/",
        "🚢 Pas de chance pour @#viewer_name# - un bruyant cargo passe et perturbe le calme de leur spot de pêche, dispersant tous les poissons.",
        "🌧️ Mauvaise nouvelle pour @#viewer_name# - une soudaine tempête de grêle rend dangereuse la poursuite de leur expédition de pêche.",
        "🎣🥖 Juste au moment où @#viewer_name# allait remonter son poisson, Mike, dans un mouvement très français, laisse accidentellement tomber une baguette dans l'eau, effrayant tous les poissons.",
        "🍎🎣 Oups ! Un des en-cas sains de Mike finit accidentellement dans l'eau, provoquant une agitation qui effraie les poissons et gâche la prise de @#viewer_name#.",
        "👞🐠 Désolé, @#viewer_name#, mais l'une des précieuses baskets de Mike vient de tomber dans l'eau, créant un éclaboussement qui effraie tous les poissons.",
        "🎶🐟😅 Juste au moment où @#viewer_name# allait remonter, ils sont enchantés par la douce mélodie de Mike jouant de la flûte, permettant aux poissons de s'échapper !",
        "🎵🐟 Pas de poisson pour @#viewer_name# cette fois. Ils étaient trop captivés par la magique performance à la flûte de Mike et ont manqué leur chance de remonter !",
        "🐟😣 Quel dommage ! @#viewer_name# a un gros poisson à la ligne, mais il est trop fort et parvient à s'échapper.",
        "⛔ Pas de chance pour @#viewer_name# - ils découvrent que le lac qu'ils voulaient pêcher est un habitat protégé, et la pêche y est strictement interdite.",
        "🎣😓 Il semble que @#viewer_name# a sous-estimé la force du courant. Leur ligne de pêche a été emportée, les laissant les mains vides.",
        "🐡 Pauvre @#viewer_name# - un phoque curieux décide de jouer avec leur appât, effrayant toutes les prises potentielles.",
        "🎣 Malheureux pour @#viewer_name# - ils ont accidentellement laissé tomber leur boîte d'accessoires de pêche dans l'eau, les laissant sans aucun équipement de pêche.",
        "🌊 Hélas ! @#viewer_name# doit abandonner leur excursion de pêche lorsqu'une marée exceptionnellement haute inonde leur spot de pêche.",
        "🦢 Inopinément, le spot de pêche de @#viewer_name# devient une zone d'atterrissage pour un vol de cygnes, effrayant efficacement les poissons.",
        "⛵ Juste au moment où @#viewer_name# était sur le point de lancer leur ligne, un jet-ski passe à toute vitesse et perturbe l'eau calme.",
        "🐟🎣 Oh non ! @#viewer_name# avait un gros poisson à la ligne, mais il a été assez malin pour voler l'appât et s'échapper.",
        "💨 Malchance pour @#viewer_name# - un fort coup de vent emporte leur chapeau, effrayant les poissons et les laissant sans prise.",
        "🌳🎣 Malheureusement, l'hameçon de @#viewer_name# se coince dans un arbre au-dessus lorsqu'ils lancent leur ligne, les laissant incapables de pêcher.",
        "🐬 Un groupe de dauphins joueurs nage à travers le spot de pêche de @#viewer_name#, dispersant les poissons dans toutes les directions.",
        "⚓ Oh là là ! @#viewer_name# perd leur ancre, rendant impossible de maintenir leur bateau stable pour pêcher.",
        "🎣😔 @#viewer_name# se prend la ligne dans quelque chose au fond de l'eau, perdant à la fois leur appât et leurs espoirs de capturer un poisson.",
        "🐚 Il semble que @#viewer_name# a choisi un spot abondant en crabes, mais malheureusement ils cherchaient à attraper des poissons.",
        "🌜 Mauvais timing pour @#viewer_name# - les poissons semblent mordre uniquement la nuit, et ils étaient tous prêts pour la pêche de jour.",
        "🌜 Oh non ! @#viewer_name# vient de se casser un orteil.",
        "🎣😢 Oh, quelle misfortune pour @#viewer_name# - ils ont accidentellement marché sur un rocher pointu et se sont blessé l'orteil, ce qui leur fait mal pour continuer à pêcher.",
        "🦅 Un groupe d'aigles fond sur la zone de pêche de @#viewer_name#, causant une commotion et effrayant les poissons.",
        "🚁 La tranquillité du spot de pêche de @#viewer_name# est brisée lorsqu'un hélicoptère bruyant survole, perturbant l'eau et envoyant les poissons se cacher.",
        "⛈️ Pas de chance pour @#viewer_name# - un orage soudain se lève, les forçant à abandonner leur aventure de pêche pour des raisons de sécurité.",
        "🐟😔 C'était si proche ! @#viewer_name# avait un énorme poisson à la ligne, mais il s'est détaché juste au moment où ils étaient sur le point de le remonter.",
        "⛔ Mauvaise nouvelle pour @#viewer_name# - ils découvrent trop tard que la pêche n'est pas autorisée dans la zone en raison de la saison de frai.",
        "🎣😩 Le courant de l'eau était plus fort que @#viewer_name# ne l'avait anticipé. Leur appât a été emporté, les laissant sans prise.",
        "🦦 Quelle malchance ! Une loutre joueuse décide de faire de l'appât de @#viewer_name# son jouet, effrayant le reste des poissons.",
        "🎣 Oh, la malchance ! @#viewer_name# trébuche sur une racine d'arbre et leur matériel de pêche tombe dans l'eau.",
        "🌊 Oh non ! Une vague soudaine submerge le spot de pêche de @#viewer_name#, les forçant à se retirer.",
        "🦆 Il semble que la zone de pêche de @#viewer_name# soit devenue un lieu de rassemblement pour un groupe de canards, qui ont effrayé tous les poissons.",
        "🚤 Juste au moment où @#viewer_name# allait avoir une touche, un bateau à moteur passe et la vague perturbe la zone.",
        "🐟🎣 C'est dommage ! @#viewer_name# avait une prise à la ligne, mais le poisson malin a réussi à se débattre et à s'échapper.",
        "💨 C'est la malchance pour @#viewer_name# - un coup de vent soudain a emporté leur parapluie de pêche dans l'eau, effrayant les poissons.",
        "🌳🎣 Oh non, @#viewer_name# a emmêlé leur ligne dans quelques roseaux, les laissant incapables de continuer à pêcher.",
        "🐋 Une baleine décide de faire surface près du spot de pêche de @#viewer_name#, provoquant une énorme éclaboussure et dispersant les poissons.",
        "⚓ La malchance frappe lorsque @#viewer_name# réalise qu'ils ont oublié de sécuriser l'ancre de leur bateau, le laissant dériver loin de leur spot de pêche.",
        "🎣😖 Oh non ! @#viewer_name# laisse tomber accidentellement leurs lunettes de soleil dans l'eau, effrayant tous les poissons à proximité.",
        "🐕 Juste au moment où @#viewer_name# allait avoir une grosse prise, leur chien saute dans l'eau pour chasser la ligne.",
        "🌳🎣 Oups ! @#viewer_name# lance leur ligne trop haut et elle se coince dans un arbre.",
        "🌬️ Pas de chance ! Un coup de vent soudain emporte le chapeau de @#viewer_name# dans l'eau, effrayant les poissons.",
        "🚁 Mauvais timing ! Un hélicoptère survole le spot de pêche de @#viewer_name#, faisant fuir les poissons.",
        "🐸 Quelle surprise ! Un groupe de grenouilles bruyantes choisit le spot de pêche de @#viewer_name# comme leur nouvelle scène de concert.",
        "🌊 Oh là là ! Une grande vague submerge le spot de pêche de @#viewer_name#, trempant leur sandwich.",
        "🎣😩 Tant pis ! @#viewer_name# oublie d'attacher correctement l'appât et il glisse de l'hameçon.",
        "🐟 Oups ! @#viewer_name# a une touche, mais c'est une chaussure, pas un poisson.",
        "🚤 Oh non ! Un bateau à moteur crée des vagues qui perturbent le spot de pêche paisible de @#viewer_name#.",
        "🎣😢 Hélas, @#viewer_name# perd leur chapeau de pêche porte-bonheur dans un coup de vent, les laissant sans leur charme.",
        "🌧️ Malheureusement, une averse soudaine oblige @#viewer_name# à se replier et à quitter leur spot de pêche.",
        "🦢 Pauvre @#viewer_name#, un cygne a pris goût à leur spot de pêche et ne veut plus partir, effrayant les poissons.",
        "🐟🎣 @#viewer_name# pensait avoir attrapé un gros poisson, mais il s'est avéré être une botte en caoutchouc !",
        "🎣🎮 Au moment où @#viewer_name# allait remonter un gros poisson, le cri de victoire de Mike après une intense partie de League of Legends a effrayé les poissons.",
        "🎮🥐 Distrait par l'odeur du croissant frais de Mike, @#viewer_name# ne remarque pas les poissons qui mordillent leur appât.",
        "🎮🍞 Quelle malchance ! Pendant que @#viewer_name# était occupé à regarder Mike vaincre des zombies dans DayZ, leurs poissons se sont enfuis.",
        "🎣🥐 Oh non, @#viewer_name# était trop distrait par le croissant de Mike et a manqué le gros poisson.",
        "🎣😞 Pas de chance pour @#viewer_name# - Mike allait partager sa baguette, mais il semble que les poissons étaient plus rapides.",
        "🎣😞 Malchance pour @#viewer_name# - ils ont essayé d'utiliser un morceau de la baguette de Mike comme appât, mais les poissons n'étaient pas fans de la cuisine française.",
        "🌧️🥶 Malheureusement pour @#viewer_name#, une soudaine tempête de grêle, tout comme le temps sauvage dans DayZ, rend dangereuse la poursuite de leur pêche.",
        "🦆🦆🦆 Oh là là, la tentative de pêche de @#viewer_name# est contrecarrée lorsque une famille de canards décide que c'est l'heure du repas et effraie tous les poissons !",
        "🦈😱 Une ombre plane dans l'eau, effrayant les poissons. Il s'avère que cétait juste un requin pèlerin inoffensif qui passait par là. Mieux vaudra la prochaine fois, @#viewer_name#!",
        "🌩️🌊 Juste au moment où @#viewer_name# lance leur ligne, une tempête soudaine se lève, provoquant l'agitation de la mer. Les poissons se sont tous cachés !",
        "🌕🐺🎣 Dans un étrange tournant des événements, un loup hurlant au loin pendant la pleine lune effraie tous les poissons. Désolé, @#viewer_name#!",
        "🐠🏖️☀️ Les poissons semblent avoir pris des vacances, @#viewer_name#! Le sable de plage ensoleillé au fond est vide. Pas de chance cette fois !",
        "👽🛸🐟 Inopinément, un vaisseau spatial extraterrestre apparaît et enlève tous les poissons, laissant @#viewer_name# avec une ligne vide. Peut-être la prochaine fois, cadet de l'espace !",
        "🌳🐿️ Les poissons sont partis ! Il semble qu'un écureuil espiègle sur la rive de la rivière lançait des glands dans l'eau et les effrayait. Pas de chance, @#viewer_name#!",
        "🌈🎣 La vue d'un magnifique arc-en-ciel distrait @#viewer_name# un instant, et les poissons profitent de cette chance pour s'échapper. Mieux vaudra la prochaine fois !",
        "🦢🌸🎣 Alors que @#viewer_name# était sur le point de remonter un gros poisson, un cygne passe gracieusement, effrayant les poissons. Si proche, pourtant si loin !",
        "🏔️❄️ Les poissons semblent avoir attrapé un frisson du ruisseau de montagne glacé, @#viewer_name#. Ils sont tous blottis dans un coin chaud aujourd'hui !",
        "🐶 @#viewer_name# était sur le point d'attraper un poisson, mais un chien joueur a sauté dans l'eau et a effrayé tous les poissons.",
        "⛅🎣 Juste au moment où @#viewer_name# lançait leur ligne, le soleil est sorti. La lumière vive a effrayé tous les poissons. Mieux vaudra la prochaine fois !",
        "🎈🐠 Un groupe de ballons colorés tombe dans l'eau. Les poissons ont peur et nagent loin. Désolé, @#viewer_name#!",
        "🐦🐟 Un oiseau bruyant survole l'eau, et tous les poissons nagent loin. Réessayez, @#viewer_name#!",
        "🚁🌊 Un hélicoptère survole l'eau. Le bruit effraie tous les poissons. Mieux vaudra la prochaine fois, @#viewer_name#!",
        "🦀🎣 @#viewer_name# était sur le point d'attraper un poisson, mais un gros crabe l'a effrayé. Réessayez !",
        "🏖️☀️ Il fait tellement ensoleillé, tous les poissons sont allés profondément dans l'eau pour se rafraîchir. Pas de poisson pour @#viewer_name# cette fois !",
        "🌧️🐠 Il a commencé à pleuvoir et tous les poissons ont nagé loin. Désolé, @#viewer_name#!",
        "🐉 Un dragon jouet tombe dans l'eau et effraie tous les poissons. Mieux vaudra la prochaine fois, @#viewer_name#!",
        "🛵🌊 Un jet ski rapide passe, et les vagues effraient les poissons. Réessayez, @#viewer_name#!",
        "🐸🎣🌦️⏰ Pas de chance pour @#viewer_name#, juste au moment où ils étaient sur le point d'attraper un poisson, un chœur bruyant de grenouilles effraie les poissons et une soudaine averse les oblige à ranger tôt.",
        "🐝🌼🎣💨 Juste au moment où @#viewer_name# était sur le point de remonter un poisson, une abeille bourdonne près de leur oreille, les distrayant, et une rafale de vent emporte leur chapeau, les faisant perdre leur prise.",
        "🎈🍦🎣🌊 Oh non ! Un ballon égaré effraie les poissons juste au moment où @#viewer_name# était sur le point d'en attraper un, puis la mélodie d'un camion de crème glacée les distrait, les faisant lâcher leur canne dans l'eau.",
        "🌲🐿️🎣☀️ Mauvaise chance pour @#viewer_name#. Juste au moment où ils s'apprêtaient à lancer leur ligne, un écureuil espiègle les surprend, les faisant perdre leur appât, puis le soleil sort si brillamment que tous les poissons plongent plus profondément.",
        "🚁🎣🍔🌩️ Oh là là, @#viewer_name#! Juste au moment où vous profitiez de votre session de pêche, un hélicoptère bruyant effraie les poissons, votre burger tombe dans l'eau, et un orage soudain vous fait partir.",
        "🌌🌠🎣🐕 Juste au moment où @#viewer_name# profitait d'une session de pêche paisible la nuit, une étoile filante les distrait, leur chien excité saute dans l'eau et effraie tous les poissons.",
        "🌸🎣🎈🌦️ Alors que @#viewer_name# admirait de belles fleurs, un ballon dérive dans leur zone de pêche effrayant les poissons, puis une pluie soudaine les force à arrêter de pêcher.",
        "🚗🔊🎣🐟 Mauvaise chance pour @#viewer_name#. Un klaxon de voiture bruyant effraie tous les poissons juste au moment où ils allaient avoir une touche.",
        "🌈🎣🐦🌊 Juste au moment où @#viewer_name# était sur le point de remonter un poisson, ils sont distraits par un magnifique arc-en-ciel, un vol d'oiseaux passe au-dessus, et une grande vague submerge leur spot, effrayant tous les poissons.",
        "🎣🌲🐿️🌦️ Juste au moment où @#viewer_name# était sur le point d'attraper un gros poisson, un écureuil les surprend, ils perdent leur appât dans l'eau puis il commence à pleuvoir. Quelle journée !",
        "🐢🎣🌪️🌴 Pas de chance pour @#viewer_name#, une tortue lente effraie les poissons, une tornade de poussière emporte leur chapeau, et une noix de coco tombe d'un palmier, les surprenant. Mieux vaudra la prochaine fois !",
        "🎣🐠🍦🌞 C'était une journée tellement chaude que la glace de @#viewer_name# a fondu et est tombée dans l'eau, attirant quelques poissons curieux, mais pas très affamés. Mieux vaudra la prochaine fois !",
        "🐾🎣 Oh non, @#viewer_name#! Un raton laveur curieux s'est glissé et a volé votre appât pendant que vous ne regardiez pas. Mieux vaudra la prochaine fois !",
        "🐎 Juste au moment où @#viewer_name# lançait leur ligne, un groupe de chevaux sauvages a commencé à éclabousser dans la rivière en amont, effrayant tous les poissons.",
        "🌵 Il fait trop chaud aujourd'hui ! Les poissons sont tous descendus plus profondément dans l'eau pour échapper à la chaleur. Désolé, @#viewer_name#!",
        "🎣🍂 Un vent inattendu souffle un tas de feuilles dans le spot de pêche de @#viewer_name#, effrayant tous les poissons.",
        "🚂 Un train bruyant passe à proximité, secouant le sol et faisant fuir les poissons. Mieux vaudra la prochaine fois, @#viewer_name#!",
        "🌌🎣 Malheureusement pour @#viewer_name#, les poissons semblent être plus intéressés par les étoiles filantes que par l'appât !",
        "🍦 Oups ! @#viewer_name# est distrait par un camion de glaces et manque une grosse touche à la ligne. Le poisson s'échappe !",
        "🌳 Un écureuil joueur descend de l'arbre et saute dans l'eau, effrayant les poissons. Réessayez, @#viewer_name#!",
        "⏰🎣 Oh là là ! @#viewer_name# était trop occupé à régler leur alarme de pêche et a manqué une grosse prise. Le poisson s'est échappé !",
        "🐸 Incroyable ! Pendant que Mike pêchait, Kermite la grenouille a sauté dans l'eau, effrayant les poissons et laissant la ligne vide.",
        "🍞😭 Dommage ! Mike était distrait par l'odeur d'une brioche au caramel et a manqué une touche. On dirait que le poisson s'est échappé, @#viewer_name#!",
        "🐶 Oh non ! Padi, le chien de Mike, a décidé de se baigner, et tous les poissons se sont enfuis. Mieux vaudra la prochaine fois, @#viewer_name#!",
        "🚗💨 Dommage ! Une voiture bruyante passant par là a effrayé tous les poissons aux alentours. Désolé, @#viewer_name#, il semble que les poissons ne mordent pas aujourd'hui.",
        "📬🎣 Oups ! Mike s'est mis à rêver de son prochain design de carte postale, et les poissons ont profité de l'occasion pour s'échapper. Un vrai problème d'artiste, hein, @#viewer_name# ?",
        "⚡ Zut ! Un orage soudain se lève, rendant dangereux de continuer à pêcher. @#viewer_name#, replions-nous pour des raisons de sécurité !",
        "🌙😴 Aww, pas de chance cette fois ! Mike était si fatigué après le streaming qu'il s'est endormi, laissant échapper un gros poisson. Tentons à nouveau, @#viewer_name#.",
        "🎵🙈 Oh là là ! Mike a commencé à fredonner si fort qu'il a effrayé les poissons. Mieux vaudra la prochaine fois, @#viewer_name#!",
        "🍬😔 Pas de poisson aujourd'hui, @#viewer_name#. Mike a laissé tomber un morceau de caramel dans l'eau et il semble que les poissons n'aiment pas la douceur.",
        "🖌️🐟 Désolé, @#viewer_name#, mais pas de prise aujourd'hui. Mike était occupé à esquisser le magnifique paysage, et les poissons en ont profité pour s'échapper.",
        "🐸💥 Oups ! Kermite la grenouille a sauté dans l'eau et a créé une telle éclaboussure que tous les poissons se sont enfuis. Pas de chance, @#viewer_name#!",
        "🐶🌊 Uh-oh ! Padi a décidé que c'était l'heure de jouer et a sauté dans l'eau, effrayant tous les poissons. Désolé, @#viewer_name#, nous réessaierons bientôt !",
        "🎣📦 Wow ! @#viewer_name# vient de remonter une petite boîte métallique. Pourrait-elle contenir quelque chose de précieux ? Hélas, ce ne sont que de vieux bouchons de bouteilles.",
        "🎣💼 Incroyable ! @#viewer_name# a accroché ce qui semble être un ancien cartable. Qu'y a-t-il à l'intérieur, demandez-vous ? Juste quelques vieux journaux détrempés.",
        "🎣🧳 Étonnant ! @#viewer_name# vient de remonter une valise en cuir usée. À l'intérieur ? Une poignée de galets très peu excitants.",
        "🎣🧸 Oh là là ! @#viewer_name# vient de pêcher un petit coffre verrouillé. L'anticipation monte alors qu'il s'ouvre pour révéler... un ours en peluche usé. Quel anticlimax !",
        "🎣🔓 Wahou ! @#viewer_name# vient de pêcher une vieille boîte verrouillée. Après l'avoir déverrouillée, nous trouvons... une seule clé rouillée. Quelle déception !",
        "🎣💍 Incroyable ! @#viewer_name# vient de pêcher une petite boîte en velours. Est-ce une gemme précieuse ? No, c'est une bague en plastique bon marché.",
        "🎣👑 Étonnant ! @#viewer_name# a remonté une boîte en bois ornée. À l'intérieur se trouve... une couronne en papier d'aluminium. Presque trompé !",
        "🎣🎁 Wow ! @#viewer_name# a remonté une boîte cadeau. En l'ouvrant, nous trouvons... un vieux morceau de fromage moisi.",
        "🎣🎈 Oh ! @#viewer_name# vient de pêcher un petit récipient rond. Qu'est-ce que cela pourrait être ? Juste un ballon dégonflé. Si proche, pourtant si loin !",
        "🎣💼 Incroyable ! @#viewer_name# a accroché un paquet mystérieux. À l'intérieur ? Juste une vieille montre de poche cassée",
        "🎣🎻 Incroyable ! @#viewer_name# a remonté un étui à violon. Est-ce un Stradivarius vintage ? Non, juste un vieux sandwich. Quel retournement de situation !",
        "🎣🗝️ Fascinant ! @#viewer_name# vient d'accrocher une petite boîte ornée. Elle s'ouvre pour révéler... un vieil ouvre-boîte rouillé. Eh bien, c'est décevant !",
        "🎣👠 Whoa ! @#viewer_name# vient de remonter une boîte à chaussures. Pourrait-elle contenir des chaussures de créateur ? Non, ce n'est qu'une paire de chaussettes dépareillées.",
        "🎣🍴 Étonnant ! @#viewer_name# a attrapé une boîte à lunch. Est-ce un repas gastronomique ? Loin de là. Ce n'est qu'un sandwich au thon à moitié mangé.",
        "🎣🎩 Oh là là ! @#viewer_name# vient de pêcher une boîte à chapeaux. Est-ce un fedora élégant ? Désolé, ce n'est qu'un ballon de plage dégonflé.",
        "🎣🎭 Surprenant ! @#viewer_name# vient de remonter une vieille boîte de film. Est-ce un chef-d'œuvre cinématographique perdu ? Malheureusement, ce n'est qu'une bobine de vieilles publicités.",
        "🎣🏺 Incroyable ! @#viewer_name# vient d'accrocher un pot ancien. Trésors des profondeurs ? Non, juste de la boue ancienne.",
        "🎣📚 Wow ! @#viewer_name# vient de remonter un conteneur étanche pour livres. Un chef-d'œuvre littéraire ? Malheureusement, ce n'est qu'un vieux bottin téléphonique.",
        "🎣💎 Spectaculaire ! @#viewer_name# a pêché une boîte à bijoux scintillante. Pierres précieuses ? Non, juste du joli verre de mer.",
        "🎣🎈 Intrigant ! @#viewer_name# a accroché un conteneur en forme de ballon. Des pétards à l'intérieur ? Non, juste un tas d'espoirs dégonflés.",
        "🎣🧨 Incroyable ! @#viewer_name# a remonté un petit tube qui ressemblait étrangement à un feu d'artifice. Il s'est avéré être... une banane trop mûre. Eh bien, cétait inattendu !",
        "🎣🎳 Oh là là ! @#viewer_name# vient d'accrocher ce qui semble être un sac de boule de quilles. Est-ce une boule de quilles haut de gamme ? Non, juste une famille de souris des champs surprises !",
        "🎣🧦 Fascinant ! @#viewer_name# vient de remonter une vieille chaussette. Que pourrait-elle contenir ? Seulement du sable humide et un peu trop d'algues.",
        "🎣👓 Wow ! @#viewer_name# vient de pêcher un étui à lunettes. Espérant une paire de créateur ? Pas de chance, il est juste rempli de vers gommeux acides !",
        "🎣🥾 Regardez ça ! @#viewer_name# vient de remonter une botte. Est-elle remplie de pièces d'or ? Nah, juste un crabe ermite très agacé.",
        "🎣🎈 Incroyable ! @#viewer_name# a accroché un ballon avec une note attachée. Est-ce un message secret ? Non, c'est juste un menu à emporter pour un restaurant de sushis.",
        "🎣💻 Incroyable ! @#viewer_name# vient de remonter un vieux étui d'ordinateur portable. Des espoirs élevés pour un MacBook ? Désolé, c'est juste une gaufre extrêmement détrempée.",
        "🎣🐔 Whoa ! @#viewer_name# vient de pêcher... un poulet en caoutchouc ? Eh bien, c'est la pêche pour vous. Toujours plein de surprises !",
        "🎣📻 Wow ! @#viewer_name# vient de remonter une vieille radio. Fonctionne-t-elle encore ? Pas tout à fait. Elle bourdonne juste avec le son des abeilles !",
        "🎣🎺 Oh ! @#viewer_name# vient d'accrocher ce qui semble être un étui à trompette. Peut-être un instrument en laiton rare ? Non, juste un perroquet très vocal !",
        "🎣🧳🔮 Étonnant ! @#viewer_name# vient de remonter une valise couverte de poussière. Que pourrait-elle contenir ? Juste quelques vieux vêtements rongés par les mites. Quelle déception !",
        "🎣📦😲 Incroyable ! @#viewer_name# vient de remonter une petite boîte dorée. Elle doit être pleine de trésors, n'est-ce pas ? Non, juste un tas de pièces ternies.",
        "🥱😴 @#viewer_name# est tellement fatigué de pêcher...",
        "🎣🛍️🤔 Intéressant ! @#viewer_name# vient de pêcher une pochette argentée brillante. Sûrement, elle contient quelque chose de précieux ? Non, juste un tas de vieux reçus d'épicerie.",
        "🎣📚💼🙄 Oh là là ! @#viewer_name# vient de pêcher un lourd conteneur en forme de livre. Un roman rare peut-être ? Non, juste un vieux bottin téléphonique.",
        "🎣💼💎🤭 Wow ! @#viewer_name# a accroché une boîte en bois sculptée de manière complexe. À l'intérieur... une collection de bijoux de fantaisie. Presque trompé là-bas !",
        "🎣📦🤨 Qu'est-ce que c'est ? @#viewer_name# vient de remonter un coffre noir battu par les intempéries. Pourrait-il s'agir d'un trésor de pirate ? Nah, juste une horde de clous rouillés.",
        "🎣🧺😯 Aha ! @#viewer_name# vient de remonter un panier tressé scellé avec de l'argile. Des reliques précieuses peut-être ? Non, juste un tas de fleurs séchées.",
        "🎣📦😧 Incroyable ! @#viewer_name# vient de pêcher une boîte en velours cramoisi. À l'intérieur se trouve... un seul biscuit détrempé. Plutôt anticlimatique.",
        "🎣🎁😮 Quoi ?! @#viewer_name# vient d'accrocher une délicate boîte en porcelaine. Elle s'ouvre pour révéler... un vieux jouet à mâcher pour chien.",
        "🎣📦🙃 Comme c'est étrange ! @#viewer_name# vient de pêcher une petite boîte en fer blanc. Que pourrait-elle contenir ? Juste quelques boutons dépareillés.",
        "🎣📦🔎 Fascinant ! @#viewer_name# vient de remonter une boîte en carton solide. Que pourrait-il y avoir à l'intérieur ? Malheureusement, juste une miche de pain détrempée.",
        "🎣🗃️😲 Incroyable ! @#viewer_name# vient d'accrocher une vieille boîte à fichiers. Sûrement, elle contient des documents secrets ? Non, juste quelques formulaires fiscaux périmés.",
        "🎣🔒🤔 Intrigant ! @#viewer_name# vient de remonter une petite boîte verrouillée. Quels trésors pourrait-elle contenir ? À l'ouverture, c'est juste un tas de clés rouillées.",
        "🎣📦😧 Wow ! @#viewer_name# vient de pêcher une magnifique boîte en bois pe des trésors ? ☂️",
        "😢 @#viewer_name#, une autre canne à pêche ? Quelqu'un d'autre doit avoir la même chance que nous. NotLikeThis",
        "😯 @#viewer_name#, qu'y a-t-il dans cette boîte mystérieuse que vous avez pêchée ? Pourrait-ce être un trésor ? PogChamp",
        "NotLikeThis @#viewer_name#, vous avez remonté un autre conteneur... J'espère que ce n'est pas une autre vieille boîte de haricots ! 😬",
        "Jebaited @#viewer_name#, ce bocal scellé que vous avez remonté brille... Osons-nous l'ouvrir ? 😳",
        "😱 @#viewer_name#, est-ce une vieille boîte de munitions ? Faites attention avec ça ! WutFace",
        "4Head @#viewer_name#, vous avez trouvé un autre coffre en métal ? Peut-être qu'il est plein d'or de pirate ! 🏴‍☠️",
        "FailFish @#viewer_name#, vous avez attrapé un coffre, mais il est plein de vieux matériel de pêche... ironique. 🎣",
        "Kappa @#viewer_name#, ce mystérieux caisson... Pourrait-il contenir une technique de pêche secrète ? 🤔",
        "😮 @#viewer_name#, un caisson de qualité militaire dans le lac ? Je me demande ce qu'il y a à l'intérieur. PogChamp",
        "LUL @#viewer_name#, une autre bouteille avec un message à l'intérieur ? Peut-être est-ce un appel à l'aide d'un insulaire échoué ! 🏝️",
        "WutFace @#viewer_name#, que pourrait-il y avoir dans cette urne ancienne ? Espérons que ce n'est pas une malédiction ! 😨",
        "FailFish @#viewer_name#, ce n'est pas un poisson... C'est un sac en plastique ! 🛍️",
        "NotLikeThis @#viewer_name#, un emballage de restauration rapide ? Le lac n'est pas une poubelle ! 🍔😠",
        "Jebaited @#viewer_name#, venez-vous de remonter un vieux pneu ? Gardez le lac propre ! 🚗",
        "DansGame @#viewer_name#, sont-ce... des couches sales ? Beurk ! 😷",
        "😂 @#viewer_name#, vous avez attrapé une autre canette de soda ! Peut-être devriez-vous commencer une entreprise de recyclage ? 🥤",
        "🤢 @#viewer_name#, cette vieille chaussure ne semble pas avoir été perdue depuis longtemps. Kappa",
        "😯 @#viewer_name#, est-ce un vieux vélo ? Je me demande comment il est arrivé là. 4Head",
        "WutFace @#viewer_name#, un morceau de meuble pourrissant ? Comme c'est étrange ! 🛋️",
        "LUL @#viewer_name#, une autre bouteille en plastique ? Votre chance n'est pas terrible aujourd'hui. 🍼",
        "🙈 @#viewer_name#, c'est beaucoup de sacs de shopping que vous remontez. Espérons attraper un poisson la prochaine fois ! FailFish",
        "FailFish @#viewer_name#, ce n'est pas un poisson... c'est un morceau de viande pourrie et visqueuse ! 🤮",
        "😳 @#viewer_name#, vous venez de remonter une carcasse d'oiseau putride. Comment cela est-il arrivé là ? WutFace",
        "Jebaited @#viewer_name#, avez-vous sérieusement remonté un sac rempli de déchets infestés de vers ? 😱",
        "DansGame @#viewer_name#, vous avez attrapé un crâne recouvert de moisissures. Beurk ! 💀",
        "😨 @#viewer_name#, ce fromage en décomposition et puant que vous avez remonté attire les mouches ! LUL",
        "🤢 @#viewer_name#, vous avez remonté une boîte rouillée et visqueuse remplie d'une substance inconnue et nauséabonde. NotLikeThis",
        "4Head @#viewer_name#, vous avez pêché un ventre de poisson gonflé et pourri rempli de vers. Tellement dégoûtant ! 🐟",
        "😷 @#viewer_name#, vous avez accroché un rat pourri et visqueux. Quelle malchance ! FailFish",
        "🤮 @#viewer_name#, est-ce un tentacule coupé et en décomposition ? Quelque chose de terrible est dans ces eaux. WutFace",
        "Kappa @#viewer_name#, vous avez pêché un sac suintant de légumes pourris. Ce n'est pas le genre de vert que vous espériez ! 🥦",
        "✨🍌WutFace @#viewer_name#, vous avez accroché une peau de banane couverte de moisissure. Pas le trésor tropical que vous espériez ! 😷",
        "FailFish @#viewer_name#, vous avez attrapé une autre peau de banane ! Peut-être qu'un singe les jette dans le lac ? 🍌🐒",
        "4Head @#viewer_name#, avez-vous sérieusement juste remonté un téléphone banane ? 🍌☎️ hahaha ding dang ding dang dong BANANAA PHOOOOOOONE",
        "Jebaited @#viewer_name#, un autre hameçon vide !",
        "🤦‍♂️ @#viewer_name#, c'est une botte en caoutchouc, pas un poisson ! LUL",
        "🥴 @#viewer_name#, un autre amas d'algues ? FailFish",
        "WutFace @#viewer_name#, une boîte de conserve rouillée à nouveau ?",
        "😆 @#viewer_name#, venez-vous de remonter un pneu ? NotLikeThis",
        "😅 @#viewer_name#, une autre canne à pêche cassée ? Kappa",
        "🥱 @#viewer_name#, c'est juste un morceau de bois flotté. 4Head",
        "😭 @#viewer_name#, le gros est parti. FailFish",
        "😖 @#viewer_name#, accroché un autre amas d'algues ? DansGame",
        "LUL @#viewer_name#, vous pêchez maintenant de vieux clés ?",
        "🎣 @#viewer_name#, c'est un enchevêtrement de ligne de pêche ! FailFish",
        "😂 @#viewer_name#, vous avez attrapé un sac en plastique, pas un poisson ! Jebaited",
        "🐟 @#viewer_name#, c'est une feuille flottante, pas un poisson. NotLikeThis",
        "🤡 @#viewer_name#, un autre vieille canette de soda ? Vraiment ? WutFace",
        "🍾 @#viewer_name#, vous avez accroché une bouteille en verre, pas une truite ! LUL",
        "😕 @#viewer_name#, un journal détrempé ? Réessayez. FailFish",
        "😐 @#viewer_name#, un autre morceau de bois pourri ? 4Head",
        "😮 @#viewer_name#, un pneu de vélo ? C'est inattendu. Kappa",
        "😫 @#viewer_name#, avez-vous juste remonté un vieux filet ? DansGame",
        "🤯 @#viewer_name#, un autre hameçon vide ? Jebaited",
        "😣 @#viewer_name#, une autre brindille ? FailFish",
        "LUL @#viewer_name#, un morceau de plastique n'est pas un poisson !",
        "🙄 @#viewer_name#, pas une autre canette de soda ! Jebaited",
        "🗑️ @#viewer_name#, vous attrapez plus de déchets que de poissons ! DansGame",
        "🤨 @#viewer_name#, vous avez accroché un chapeau gorgé d'eau ? WutFace",
        "😲 @#viewer_name#, un conteneur d'appâts vide ? 4Head",
        "🧵 @#viewer_name#, une boule de ligne de pêche emmêlée ? Kappa",
        "🍽️ @#viewer_name#, vous avez pêché l'assiette de pique-nique de quelqu'un ! NotLikeThis",
        "😮 @#viewer_name#, une autre ancre rouillée ? LUL",
        "🤦‍♂️ @#viewer_name#, plus d'algues que de poissons aujourd'hui, hein ? FailFish",
        "🎣 @#viewer_name#, un canard en caoutchouc ? Ce n'est pas l'heure du bain ! LUL",
        "😅 @#viewer_name#, avez-vous sérieusement juste attrapé une tranche de pizza ? Qui jette ça ? Kappa",
        "🤣 @#viewer_name#, vous avez accroché un bateau jouet, pas un vrai ! FailFish",
        "🧸 @#viewer_name#, un ours en peluche ? Je pense que vous êtes au mauvais endroit pour pêcher ! Jebaited",
        "🧜‍♂️ @#viewer_name#, pêché une poupée sirène ? Mauvais type de poisson ! NotLikeThis",
        "😂 @#viewer_name# a remonté une vieille chaussure ? Vous n'êtes pas Cendrillon ! 4Head",
        "🎩 @#viewer_name#, un chapeau de magicien ? Maintenant, faites apparaître un poisson ! WutFace",
        "🛸 @#viewer_name#, un OVNI jouet ? Peut-être que les poissons sont passés interstellaires ! LUL",
        "🎈 @#viewer_name# a remonté un ballon d'eau ? 'Emyh' est écrit dessus",
        "🍩 @#viewer_name# a remonté un flotteur en forme de beignet ? Vous n'êtes pas à une fête à la piscine ! FailFish",
        "🐠 @#viewer_name#, un cracker poisson rouge ? Mauvais type de poisson doré ! LUL",
        "😂 @#viewer_name#, un poulet en caoutchouc ? Ce n'est pas un club comique ! Kappa",
        "📚 @#viewer_name#, un livre détrempé ? Peut-être que c'est Moby Dick ! FailFish",
        "🕹️ @#viewer_name# a remonté une vieille manette de jeu ? Ce n'est pas la pêche vidéo ! Jebaited",
        "🎭 @#viewer_name#, un masque comédie/tragédie ? Eh bien, ce voyage de pêche est un peu des deux ! 4Head",
        "🌂 @#viewer_name#, un parapluie ? Il ne pleut même pas ! NotLikeThis",
        "🚁 @#viewer_name#, un hélicoptère jouet ? Les poissons ont amélioré leur voyage ! WutFace",
        " cassette VHS ? Peut-être que c'est un tutoriel sur la manière de pêcher correctement ! LUL",
        "💾 @#viewer_name#, une disquette ? Vous pêchez dans une capsule temporelle technologique ! Kappa",
        "🐔 @#viewer_name#, un flotteur poulet ? Mauvais type d'oiseau ! FailFish",
        "🍼 @#viewer_name# vient de pêcher un biberon ? 'Alix' est écrit dessus. Ce n'est pas une garderie ! FailFish",
        "🎈 @#viewer_name# vient de remonter un canard en caoutchouc rose. 'Bruno' est écrit sur le dessous ! Vous pêchez, vous ne prenez pas de bain ! FailFish",
        "🦈 @#viewer_name# a remonté un requin jouet en plastique. 'Maurice' est écrit sur son ventre ! Ce n'est pas une salle de jeux pour enfants ! FailFish",
        "🏀 @#viewer_name# a remonté un basketball ? 'Wingnut' est écrit dessus. Vous n'êtes pas sur un terrain ! FailFish",
        "🪀 @#viewer_name# vient de remonter un yo-yo ? 'Aliace' est écrit sur le côté. Vous n'êtes pas sur un terrain de jeu ! FailFish",
        "🎀 @#viewer_name# vient de pêcher un nœud pour cheveux ? 'Irishugs' est écrit dessus. Ce n'est pas un salon de coiffure ! FailFish",
        "🎈 @#viewer_name# vient de remonter un canard en caoutchouc rose. 'Bruno' est écrit sur le dessous ! Vous pêchez, vous ne prenez pas de bain ! FailFish",
        "🦈 @#viewer_name# a remonté un requin jouet en plastique. 'Maurice' est écrit sur son ventre ! Ce n'est pas une salle de jeux pour enfants ! FailFish",
        "🧜‍♀️ @#viewer_name# vient de pêcher une poupée sirène. 'Mike' est écrit sur le dos ! Ce n'est pas un coffre à jouets ! FailFish",
        "🎱 @#viewer_name# a remonté une boule de billard numéro 8 ? 'Kermit' est écrit dessus. Ce n'est pas une salle de billard ! FailFish",
        "🍔 @#viewer_name# vient de remonter un flotteur en forme de hamburger ? 'Nae' est écrit sur le côté. Vous n'êtes pas à une fête BBQ ! FailFish",
        "🐙 @#viewer_name# a remonté un poulpe jouet. 'Pickle' est écrit sur sa tête ! Ce n'est pas une boutique de cadeaux d'aquarium ! FailFish",
        "🎣😢 Oups ! @#viewer_name# a essayé de remonter un gros poisson, mais il semble que le poisson ait glissé. Mieux vaudra la prochaine fois !",
        "🐟🤦‍♂️ Oh non ! @#viewer_name# avait une touche, mais le poisson s'est échappé. Continuez à essayer !",
        "🦈😞 Pas de chance ! @#viewer_name# a presque attrapé un énorme poisson, mais il a réussi à s'échapper. Restez concentré !",
        "🦐💔 Si proche ! @#viewer_name# avait une prise, mais elle a réussi à se libérer. Ne perdez pas espoir !",
        "🐡👀 Aïe ! @#viewer_name# avait une touche, mais le poisson s'est échappé. Gardez les yeux sur le prix !",
        "🎣😔 Pas de chance ! @#viewer_name# a accroché un gros poisson, mais il a sauté de retour dans l'eau. Ne renoncez pas !",
        "🐠🤷 Oups ! @#viewer_name# avait une touche, mais elle s'est échappée. Celui qui s'est échappé, hein ?",
        "🐙😕 Whoa ! @#viewer_name# avait un géant à la ligne, mais il a réussi à s'échapper. Mieux vaudra la prochaine fois !",
        "🦞🙁 Dommage ! @#viewer_name# a presque remonté une prise massive, mais elle a glissé. Ne soyez pas découragé !",
        "🦀😖 Oh non ! @#viewer_name# avait un crabe à la ligne, mais il a coupé la ligne et s'est échappé. Continuez à pêcher !",
        "☹️☹️ Zut ! @#viewer_name# était trop occupé à regarder Tam rizz up kikettebot que le poisson a glissé 🤣 LUL",
        "☹️☹️ Zut ! @#viewer_name# était trop occupé à regarder Tam rizz up kikettebot que le poisson a glissé 🤣 LUL",
        "☹️☹️ Zut ! @#viewer_name# était trop occupé à regarder Tam rizz up kikettebot que le poisson a glissé 🤣 LUL",
        "😈😈 Hahahihihihouhaha @#viewer_name#, alors vous pensiez que ce serait si facile ? DarkMode Non non non :D Nae see you 👀",
        "😈😈 Huhuhuhu @#viewer_name#, alors vous pensiez que ce serait si facile ? DarkMode Non non non ! Nae see you 👀",
        "😈😈 Houuuhahahahaah @#viewer_name#, alors vous pensiez que ce serait si facile ? DarkMode Non non non ;) Nae see you 👀",
        "🎣🐊 Aïe ! @#viewer_name# a presque attrapé un poisson, mais un crocodile rusé l'a arraché !",
        "🦖🚫 Oh non ! Le spot de pêche de @#viewer_name# a été envahi par un troupeau de petits dinosaures. Pas de poisson aujourd'hui !",
        "🎣👻 Spooky ! @#viewer_name# a essayé de remonter un poisson, mais il s'est avéré être un poisson fantôme qui a disparu !",
        "🧙‍♂️✨ Oups ! Un sorcier errant a transformé la prise de @#viewer_name# en grenouille. Ribbit !",
        "🎣🛸 Incroyable ! Un vaisseau spatial extraterrestre a enlevé le poisson de @#viewer_name# juste au moment où il était accroché !",
        "🐢💨 Ralentissez ! Une tortue rapide a effrayé tous les poissons avant que @#viewer_name# puisse en attraper.",
        "🎣🌪️ Oh là là ! Une mini tornade a emporté le matériel de pêche de @#viewer_name# dans le ciel.",
        "🐌⏳ La patience mise à l'épreuve ! @#viewer_name# a attendu si longtemps qu'un escargot a dépassé leur appât.",
        "🎣🍿 Whoops ! @#viewer_name# a été distrait par un vendeur de popcorn et a manqué les poissons qui mordaient.",
        "🎩🐇 Surprise ! Un lapin est sorti du chapeau de pêche de @#viewer_name#, effrayant les poissons.",
        "🎣🦄 Mésaventure magique ! Une licorne insaisissable est apparue, et tous les poissons se sont enfuis in admiration.",
        "🐲🔥 Uh-oh ! Le souffle de feu d'un dragon a chauffé l'eau, rendant les poissons trop chauds à manipuler pour @#viewer_name#.",
        "🎣📱 Distrait ! @#viewer_name# était trop occupé à prendre des selfies et a manqué toutes les touches.",
        "🧜‍♀️🌊 Wow ! Une sirène a demandé à @#viewer_name# de ne pas pêcher sur son territoire, alors ils ont respectueusement arrêté.",
        "🎣🍕 Oups ! @#viewer_name# a accidentellement utilisé une tranche de pizza comme appât, et maintenant les poissons font la fête sans eux.",
        "🐘 showers Splash ! Un éléphant a pris un bain juste là où @#viewer_name# pêchait, causant une belle vague.",
        "🎣🔮 Mystique ! L'appât de @#viewer_name# s'est transformé en boule de cristal. Pas de poisson, mais l'avenir semble intéressant !",
        "🐒 Des singes espiègles ont volé la canne à pêche de @#viewer_name# ! Maintenant, ils pêchent dans les arbres.",
        "🎣🌈 Si proche ! Un leprechaun a offert à @#viewer_name# un pot d'or pour arrêter la pêche. Marché accepté !",
        " Parrot a imité une sirène, effrayant tous les poissons du spot de @#viewer_name#.",
        "🎣🕰️ Retour dans le temps ! @#viewer_name# a lancé leur ligne et elle est retournée dans le temps. Les poissons n'étaient pas encore là !",
        "🐿️🎣 Encore raté ! Un écureuil a pensé que l'appât de @#viewer_name# était une noix et s'en est emparé.",
        "🎣 Volcan sous-marin est entré en éruption, et @#viewer_name# a décidé que la pêche pouvait attendre.",
        "🦘 Rebondi ! Un kangourou a sauté et a accidentellement poussé @#viewer_name# dans l'eau.",
        "🎣🧲 Magnétisé ! L'hameçon de @#viewer_name# s'est collé à un aimant géant sous l'eau. Pas de poisson aujourd'hui.",
        "🦔🎈 Oh non ! Un hérisson flottait sur un ballon, l'éclatant et causant une éclaboussure qui a effrayé les poissons.",
        "🎣🎃 Spooooky ! Un jack-o'-lantern a fait surface, souriant à @#viewer_name# et envoyant les poissons fuir.",
        "🐕‍🦺 Whoops ! Un chien serviable a récupéré la ligne de @#viewer_name# hors de l'eau, pensant que cétait un bâton.",
        "🎣🌠 Faites un vœu ! Une étoile filante a distrait @#viewer_name#, et les poissons ont pris l'appât sans l'hameçon.",
        "🦄💨 Chaos mythique ! Une licorne a éternué, créant un arc-en-ciel qui a effrayé les poissons loin de @#viewer_name#.",
        "🎣👾 Envahi ! Des envahisseurs de l'espace en pixels sont descendus, et les poissons de @#viewer_name# se sont transformés en personnages 8 bits.",
        "🐺🌕 Un bon moment pour hurler ! Des loups ont hurlé à la pleine lune, et les poissons de @#viewer_name# se sont transformés en poissons-garous et se sont enfuis.",
        "🎣🍄 Enchanté ! @#viewer_name# a accidentellement utilisé un champignon magique comme appât, et les poissons ont commencé à voler !",
        "🐉 Zut ! Un petit dragon a pensé que leur leurre était un trésor et s'est envolé avec.",
        "🎣💤 Fête de la sieste ! @#viewer_name# s'est endormi, et les poissons ont organisé un défilé autour du bateau.",
        "🦅 Arraché ! Un aigle a plongé et a attrapé le poisson juste sur l'hameçon de @#viewer_name#.",
        "🎣🕷️ Beurk ! Une araignée géante a tissé une toile sur le spot de pêche de @#viewer_name#, et les poissons n'en sont pas fans.",
        "😂 Farceur ! Des dauphins ont joué des tours à @#viewer_name#, nouant des nœuds dans la ligne de pêche.",
        "🍭 Douce surprise ! @#viewer_name# a utilisé une sucette comme appât, attirant uniquement des crabes friands de sucreries.",
        "🦥 Trop lent ! Un paresseux a pris le contrôle de la canne à pêche de @#viewer_name#. À ce rythme, aucun poisson ne sera attrapé.",
        "🎣🌌 Cosmique ! Un trou noir est brièvement apparu, avalant l'appât de @#viewer_name# et les poissons avec.",
        "🦀🦀 Problèmes doubles ! Deux crabes ont pincé les orteils de @#viewer_name#, les faisant lâcher la canne à pêche.",
        "🎣👑 Décret royal ! Le Roi des Poissons a déclaré qu'aucune pêche n'était autorisée aujourd'hui, et @#viewer_name# a dû s'y conformer.",
        " brontosaure pataugé dans la rivière, créant des vagues qui ont perturbé la pêche de @#viewer_name#.",
        "🎣🍀 Malchance ! @#viewer_name# a trouvé un trèfle à quatre feuilles, mais cétait en fait un signe de jour de vacances pour les poissons.",
        "🐧 Slippery ! Des pingouins ont glissé dans le spot de pêche de @#viewer_name#, s'amusant beaucoup mais effrayant les poissons.",
        "🎣 Zombie fish ! Un groupe de poissons zombies a fait surface, et @#viewer_name# a décidé qu'il était temps de partir.",
        "🦔🎈 Pop ! Un hérisson sur un ballon a effrayé les poissons lorsqu'il a atterri près de @#viewer_name#.",
        "📚 Temps d'étude ! Un banc de poissons a nagé trop vite - ils étaient en retard pour la classe de poissons, laissant @#viewer_name# les mains vides.",
        "🦋✨ Enchanté ! Un essaim de papillons a distrait @#viewer_name#, et les poissons ont saisi l'occasion pour s'échapper.",
        "🎣🏖️ Journée plage ! Tous les poissons bronzent ailleurs, laissant @#viewer_name# avec un hameçon vide.",
        "🐸🎶 Ribbit ! Des grenouilles ont commencé un concert, et le bruit a éloigné les poissons du spot de @#viewer_name#.",
        "🎣🥁 Roulement de tambour, s'il vous plaît ! Juste au moment où @#viewer_name# allait attraper un poisson, une fanfare a défilé.",
        "🦔🍎 Sournois ! Un hérisson a volé l'appât de @#viewer_name#, le prenant pour une pomme savoureuse.",
        "🎣🌕 Magie lunaire ! Le reflet de la lune a confondu @#viewer_name#, et ils ont lancé la ligne sur la terre ferme.",
        "🐵🙈 Singeries ! Des singes ont échangé l'appât de @#viewer_name# avec des bananes, attirant seulement des mouches à fruits.",
        "🎣🚀 Décollage ! Un lancement de fusée a secoué la zone, et les vibrations ont effrayé tous les poissons.",
        "🦚🎨 Interruption artistique ! Un paon a déployé ses plumes, et @#viewer_name# a été distrait par les couleurs.",
        "⚽ But ! Un ballon de soccer égaré a atterri dans l'eau, et la ligne de @#viewer_name# s'est emmêlée dedans.",
        "🦒 Giraffe prise une longue gorgée d'eau, causant des ondulations qui ont envoyé les poissons se disperser.",
        "🎣🍌 Situation glissante ! @#viewer_name# a glissé sur une peau de banane et a laissé tomber la canne à pêche dans l'eau.",
        "🐚📞 Sonnerie de téléphone coquillage ! L'océan a appelé, et @#viewer_name# a manqué sa chance en répondant.",
        "🎣🦄 Double prise ! Attendez, était-ce un poisson ou une licorne qui nageait ? @#viewer_name# est trop confus pour continuer.",
        "🦔💤 Temps de sieste ! Un hérisson s'est enroulé sur le pied de @#viewer_name#, et ils n'ont pas voulu le déranger.",
        "🎣🌋 Point chaud ! Un volcan sous-marin a réchauffé l'eau, et les poissons ont décidé de passer une journée au spa ailleurs.",
        "🐢🎉 Temps de fête ! Des tortues ont organisé une fête surprise, et @#viewer_name# n'était pas sur la liste des invités.",
        "🎣🎈 En l'air ! Des ballons ont légèrement soulevé le bateau de @#viewer_name#, rendant la pêche difficile.",
        "🦘💨 Saut effrayant ! Un kangourou s'entraînant à la boxe près de @#viewer_name#, et l'agitation a effrayé les poissons.",
        "🎣📸 Dites cheese ! Un bateau de touristes a provoqué une frénésie photographique, et le flash a effrayé les poissons.",
        "🐙🤹 Spectacle de talent ! Un poulpe a commencé à jongler avec des coquillages, et @#viewer_name# a rejoint le public, oubliant de pêcher.",
        "🎣🎹 Poissons musiciens ! Les poissons ont formé un groupe sous l'eau, et @#viewer_name# s'est perdu dans les mélodies.",
        "🐌 Slow news day ! Des escargots ont passé @#viewer_name#, si vous pouvez le croire, les distrayant de la pêche.",
        "💡 Moment d'illumination ! @#viewer_name# a réalisé qu'ils avaient oublié d'appâter l'hameçon - pas étonnant qu'il n'y ait pas eu de morsures !",
        "🦢🕺 Concours de danse ! Des cygnes ont commencé à danser, et @#viewer_name# n'a pas pu s'empêcher de se joindre.",
        "🌄 Spectacle au lever du soleil ! Le magnifique lever de soleil a captivé @#viewer_name#, et les poissons ont saisi l'occasion de s'échapper.",
        "🐻 Bear alert ! Un ours amical a offert des conseils de pêche, mais a effrayé les poissons.",
        "🎣🥾 Botté ! @#viewer_name# a remonté une vieille botte, et les poissons ont ri en passant.",
        "🦔🚴 Rapide ! Un hérisson sur un petit vélo a zoomé devant @#viewer_name#, causant toute une distraction.",
        "🎣🌴 Problème tropical ! Une noix de coco est tombée sur la tête de @#viewer_name#, et les poissons ont saisi l'occasion de fuir.",
        "🐬🎩 Spectacle de magie ! Des dauphins ont réalisé des tours qui ont hypnotisé @#viewer_name#, les faisant oublier la pêche.",
        "🎣🗺️ Perdu en mer ! @#viewer_name# a réalisé qu'ils regardaient la carte à l'envers - pas étonnant que les poissons ne mordaient pas.",
        "🚢 Oh non ! Juste au moment où @#viewer_name# lançait leur ligne, le navire de Paul Watson est passé, appelant tout le monde à protéger la vie marine. Pêche reportée !",
        "🐋🚫 @#viewer_name# était sur le point de remonter un gros poisson, mais Paul Watson est apparu, leur rappelant que cette zone est un sanctuaire marin !",
        "🎣🛥️ Surprise ! Le navire de Paul Watson est arrivé, et @#viewer_name# a décidé de rejoindre les efforts de conservation au lieu de pêcher.",
        "📢 Alors que @#viewer_name# attendait une touche, Paul Watson a annoncé une manifestation amicale pour les poissons, et tous les poissons semblaient d'accord !",
        "🎣🌊 Juste au moment où @#viewer_name# pensait avoir une prise, l'équipe de Paul Watson a commencé un rassemblement pour protéger les poissons. Les poissons ont compris l'allusion !",
        "🚫🐠 Le spot de pêche de @#viewer_name# a été déclaré zone sans pêche par Paul Watson lui-même. Temps de trouver un nouveau hobby !",
        "🎣🦈 Aïe ! Paul Watson a informé @#viewer_name# qu'ils avaient presque attrapé une espèce en danger. Équipement de pêche à terre !",
        "🐬📣 @#viewer_name# a entendu Paul Watson plaider pour les dauphins à proximité. Distraits, ils ont manqué leur chance d'attraper un poisson.",
        "🌍 Paul Watson a invité @#viewer_name# à rejoindre sa mission pour sauver les océans. La pêche peut attendre ; la planète a besoin d'aide !",
        "🐳💨 Une baleine a fait surface près de @#viewer_name#, et Paul Watson a fait signe de lui donner de l'espace. Les poissons en ont profité pour s'échapper.",
        "🎣🚫 Oups ! Paul Watson a rappelé à @#viewer_name# que des pratiques de pêche durables sont essentielles. Temps de vérifier à nouveau ce permis de pêche !",
        "🐠✌️ Juste au moment où @#viewer_name# était sur le point d'attraper quelque chose, Paul Watson a commencé un rassemblement pacifique pour les droits des poissons. Les poissons semblaient reconnaissants !",
        "🎣🕊️ Inspiré par le message de Paul Watson, @#viewer_name# a décidé de relâcher leur prise dans la nature. Un geste noble !",
        "🛡️ L'équipe de Paul Watson a mis en place des filets de protection pour sauvegarder les poissons, laissant @#viewer_name# avec un hameçon vide.",
        "🎣📺 Les dernières nouvelles ! Le dernier documentaire de Paul Watson a été diffusé, et @#viewer_name# s'est tellement pris au jeu qu'ils ont oublié la pêche.",
        "🐢 ambulance @#viewer_name# a rejoint Paul Watson dans le sauvetage d'une tortue de mer échouée. Plans de pêche reportés pour une bonne cause !",
        "🎣🌞 Une annonce soudaine de Paul Watson sur un nettoyage de plage a distrait @#viewer_name#, et les poissons sont partis libres.",
        "🐙🔍 En pêchant, @#viewer_name# a repéré Paul Watson étudiant la vie marine. Curiosité piquée, ils sont allés en savoir plus.",
        "🎤 Paul Watson donnait un discours à proximité, et @#viewer_name# a décidé d'écouter au lieu de pêcher. Éducation sur l'occupation !",
        "🐡🛡️ Alerte ! Paul Watson a informé @#viewer_name# d'un rare poisson-globe dans la zone. Mieux vaut ne pas le déranger !",
        "🎣🌪️ Un tourbillon d'activité ! L'équipe de Paul Watson a commencé un événement de préservation des océans, et @#viewer_name# s'est laissé emporter par l'excitation.",
        "👋 Alors que @#viewer_name# lançait leur ligne, Paul Watson a fait signe et a suggéré de rejoindre les efforts de conservation. Pêche reportée !",
        "🚴 @#viewer_name# a rejoint Paul Watson dans une course caritative pour la conservation des océans, laissant derrière eux leur matériel de pêche.",
        "🐳📸 Paul Watson a signalé une opportunité d'observation des baleines, et @#viewer_name# a échangé leur canne contre un appareil photo.",
        "🎣🌟 Starstruck ! @#viewer_name# a rencontré Paul Watson et a obtenu un autographe, oubliant tout sur la pêche.",
        "🤝 Collaboration ! @#viewer_name# a collaboré avec Paul Watson sur un projet de vie marine. Les poissons ont apprécié le jour de congé !",
        "🎣📚 Inspiré par le livre de Paul Watson, @#viewer_name# a décidé de lire au lieu de pêcher. Le savoir, c'est le pouvoir !",
        "🎈 Un festival favorable aux poissons organisé par Paul Watson a détourné l'attention de @#viewer_name#. Temps de célébrer la vie marine !",
        "🥁 Tambour ! Le groupe de Paul Watson a commencé à jouer pour sensibiliser, et @#viewer_name# n'a pas pu résister à la musique.",
        "🐋🗺️ Paul Watson a invité @#viewer_name# à suivre une aventure de suivi de la migration des baleines. La pêche peut attendre !",
        "🎣🌊 Marées hautes ! Paul Watson a expliqué l'impact des marées sur les écosystèmes marins, et @#viewer_name# a décidé d'observer plutôt.",
        "🐠💙 Inspiré par la passion de Paul Watson, @#viewer_name# a promis de protéger les océans plutôt que de pêcher aujourd'hui.",
        "🎣📝 @#viewer_name# a commencé à écrire un blog sur la conservation des océans après une discussion avec Paul Watson. La canne à pêche se repose pour l'instant.",
        "🐳🎈 Temps de célébration ! Paul Watson a organisé un défilé pour la vie marine, et @#viewer_name# s'est joint, laissant la pêche pour un autre jour.",
        "🚴‍♀️ @#viewer_name# a participé à la course caritative de Paul Watson le long de la plage, laissant derrière lui son matériel de pêche pour une bonne cause.",
        "🌿 Paul Watson a montré à @#viewer_name# un site de nidification de tortues de mer, et ils ont choisi d'aider à le protéger plutôt que de pêcher.",
        "🎣💡 Éclairé ! Après avoir entendu Paul Watson parler, @#viewer_name# a repensé ses habitudes de pêche pour la durabilité.",
        "🐙📖 @#viewer_name# a été captivé par un livre de biologie marine recommandé par Paul Watson, reportant leur excursion de pêche.",
        "🚮 Inspiré par Paul Watson, @#viewer_name# a commencé à ramasser les déchets le long du rivage. Les poissons semblent déjà plus heureux !",
        "🎥 Lumières, caméra, action ! @#viewer_name# a aidé Paul Watson à filmer un segment de documentaire, oubliant la pêche.",
        "🎣👷 Détour ! Paul Watson a recruté @#viewer_name# pour aider à construire un récif artificiel. Un échange valable.",
        "🌅 Hypnotisé par la beauté de la mer mise en lumière par Paul Watson, @#viewer_name# a décidé de simplement profiter de la vue.",
        "🎣🦜 Un perroquet de l'équipage de Paul Watson a tenu compagnie à @#viewer_name#, bavardant et effrayant les poissons.",
        "🐳🌠 Observation des étoiles ! Paul Watson a montré à @#viewer_name# des constellations, et la pêche est passée au second plan.",
        "🎣🏝️ Naufragé ! @#viewer_name# a rejoint Paul Watson lors d'une expédition sur une île éloignée, ne laissant aucun temps pour la pêche.",
        "🎨 Attaque artistique ! Inspiré par Paul Watson, @#viewer_name# a peint une fresque pour sensibiliser à la conservation des océans.",
        "🔧 Changement de matériel ! Paul Watson a aidé @#viewer_name# à mettre à niveau leur équipement pour une pêche durable, mais la lumière du jour a disparu.",
        "🐋🌈 Observation d'arc-en-ciel ! Paul Watson et @#viewer_name# ont regardé un arc-en-ciel sur l'océan, rendant la pêche moins importante.",
        "🕶️ À la mode ! Paul Watson a offert à @#viewer_name# des lunettes de soleil écologiques, et ils ont passé la journée à admirer la vue.",
        "📆 Tournage du calendrier ! @#viewer_name# a aidé Paul Watson avec un calendrier de la vie marine, oubliant la pêche.",
        "🎣🍃 Devenir vert ! Inspiré par Paul Watson, @#viewer_name# a décidé de planter des arbres au lieu de pêcher aujourd'hui.",
        " Correspondants ! Paul Watson a connecté @#viewer_name# avec des conservationnistes internationaux, suscitant de nouveaux intérêts.",
        "🎈 Interdiction des ballons ! Ensemble avec Paul Watson, @#viewer_name# a fait campagne contre les ballons polluants les océans, ne laissant aucun temps pour pêcher.",
        " Mission mondiale ! @#viewer_name# a rejoint l'initiative mondiale de Paul Watson, mettant la pêche en pause.",
        "🪈👀 @#viewer_name# a accroché une flûte avec une note à l'intérieur disant 'Pas de banane ici !'. Lilypeach a encore tenté de jouer de la flûte sous l'eau. Silly Lily !",
        "🪈👀 @#viewer_name# a accroché une flûte mignonne avec une note à l'intérieur disant 'Pas de banane ici !'. Lilypeach a encore tenté de jouer de la flûte sous l'eau. Silly Lily :D",
        "🪈👀 @#viewer_name# a trouvé une GRANDE flûte avec une note à l'intérieur disant 'Pas de banane ici, désolé désolé !'. Lilypeach a essayé de jouer cette GRANDE flûte sous l'eau mais... Silly Lily :P"
    ]
}

pub fn get_fish_data() -> HashMap<Rarity, Vec<FishData>> {
    let mut data = HashMap::new();

    // COMMON
    data.insert(Rarity::Common, vec![
        fish("Sardine", 5.0, 10.0, 2.5, vec![
            ("badly damaged", vec!["🔴 Elle semble avoir été écrasée, pauvre petite.", "🔴 Cette sardine a clairement vu des jours meilleurs, totalement écrasée."]),
            ("damaged", vec!["🟠 Une sardine un peu cabossée mais encore mangeable.", "🟠 Elle a subi quelques chocs, mais elle reste comestible."]),
            ("worn", vec!["🟡 Elle est correcte, sans être remarquable.", "🟡 Une sardine usée, mais toujours acceptable pour la consommation."]),
            ("good", vec!["🟢 Une belle sardine, parfaite pour le gril.", "🟢 Fraîche et juteuse, cette sardine est prête pour une cuisson parfaite."]),
            ("pristine", vec!["✨ Un spécimen presque parfait, d'une brillance éclatante.", "✨ Impeccable et lumineuse, elle est idéale pour une présentation soignée."]),
        ]),
        fish("Bar Commun", 20.0, 40.0, 10.0, vec![
            ("badly damaged", vec!["🔴 Ce bar semble avoir survécu à de nombreuses batailles... Un guerrier.", "🔴 Marqué par des combats féroces, ce bar a clairement souffert mais il tient encore debout !"]),
            ("damaged", vec!["🟠 Il a des cicatrices visibles, mais reste un bon poisson avec de belles écailles.", "🟠 Bien que griffé et cicatrisé, il reste noble dans son allure."]),
            ("worn", vec!["🟡 Un bar robuste, avec quelques marques du temps.", "🟡 Malgré l'usure, ce bar garde une belle prestance."]),
            ("good", vec!["🟢 En pleine santé, ses écailles brillent sous la lumière.", "🟢 Un spécimen robuste et luisant, prêt pour le marché."]),
            ("pristine", vec!["✨ Un bar magnifique, digne d'une photo souvenir.", "✨ Parfait en tout point, ce bar est la star de l'océan."]),
        ]),
        fish_simple("Carassin", 10.0, 25.0, 5.0, vec![
            ("badly damaged", "🔴 Un carassin abîmé, son parcours a dû être difficile."),
            ("damaged", "🟠 Un poisson qui montre des signes d'usure, mais reste appétissant."),
            ("worn", "🟡 Il semble en bonne condition, mais sans grande particularité."),
            ("good", "🟢 Un joli carassin, brillant et robuste."),
            ("pristine", "✨ Un spécimen parfait, ses écailles dorées éclatent sous la lumière."),
        ]),
        fish_simple("Brème", 15.0, 30.0, 6.0, vec![
            ("badly damaged", "🔴 La brème est en piteux état, ses écailles sont éraflées."),
            ("damaged", "🟠 Quelques marques de griffures sur son corps."),
            ("worn", "🟡 Une brème normale, rien d'extraordinaire."),
            ("good", "🟢 Une belle brème, brillante et en bonne forme."),
            ("pristine", "✨ Une prise parfaite, sa nageoire dorsale est intacte et élégante."),
        ]),
        fish_simple("Rotengle", 12.0, 25.0, 7.0, vec![
            ("badly damaged", "🔴 Ses nageoires sont abîmées et son corps montre des signes de lutte."),
            ("damaged", "🟠 Un poisson robuste, malgré quelques marques visibles."),
            ("worn", "🟡 Il a fière allure, bien qu'un peu usé."),
            ("good", "🟢 Un rotengle en pleine forme, parfait pour une belle prise."),
            ("pristine", "✨ Ses nageoires rouges et son corps doré sont parfaits, une prise exceptionnelle."),
        ]),
        fish_simple("Perche Soleil", 5.0, 15.0, 4.0, vec![
            ("badly damaged", "🔴 La perche est abîmée, ses couleurs sont ternies."),
            ("damaged", "🟠 Elle montre quelques signes de lutte, mais reste vive."),
            ("worn", "🟡 Une petite perche mignonne, avec des couleurs délavées."),
            ("good", "🟢 Ses écailles scintillent comme un rayon de soleil."),
            ("pristine", "✨ Une perche magnifique, éclatante de couleurs vives."),
        ]),
        fish_simple("Chevesne", 15.0, 35.0, 8.0, vec![
            ("badly damaged", "🔴 Ce chevesne a l'air d'avoir traversé une tempête."),
            ("damaged", "🟠 Un poisson avec des marques d'usure sur son flanc."),
            ("worn", "🟡 Un chevesne robuste, sans défaut majeur."),
            ("good", "🟢 Une belle prise, vigoureuse et éclatante."),
            ("pristine", "✨ Parfaitement intact, un chevesne digne des meilleures rivières."),
        ]),
        fish_simple("Éperlan", 8.0, 15.0, 3.0, vec![
            ("badly damaged", "🔴 Ce petit éperlan semble avoir eu une vie difficile."),
            ("damaged", "🟠 Quelques écailles manquent, mais il reste en bon état."),
            ("worn", "🟡 Un poisson correct, sans grande particularité."),
            ("good", "🟢 Un bel éperlan, brillant et plein de vitalité."),
            ("pristine", "✨ Un éperlan parfait, un vrai reflet d'argent dans l'eau."),
        ]),
        fish_simple("Crapet", 7.0, 15.0, 3.0, vec![
            ("badly damaged", "🔴 Le crapet semble avoir été malmené par d'autres poissons."),
            ("damaged", "🟠 Quelques marques visibles, mais il reste vigoureux."),
            ("worn", "🟡 Un crapet banal, mais en bonne condition."),
            ("good", "🟢 Ses écailles brillent sous la lumière, un bel exemplaire."),
            ("pristine", "✨ Un crapet éclatant, parfaitement proportionné."),
        ]),
        fish("Têtard", 0.1, 1.0, 0.5, vec![
            ("badly damaged", vec![
                "🔴 Ce têtard a clairement eu des débuts difficiles, marqué par les épreuves de la vie aquatique.",
                "🔴 Visiblement, ce petit têtard a échappé de justesse à un destin funeste. Il porte les cicatrices de sa lutte pour la survie.",
                "🔴 À peine plus qu'une queue frétillante, ce têtard porte les stigmates d'une rude introduction au monde aquatique."
            ]),
            ("damaged", vec![
                "🟠 Ce têtard porte quelques égratignures, témoignage des petites batailles qu'il a dû mener.",
                "🟠 Légèrement meurtri, ce petit têtard a déjà affronté des défis considérables.",
                "🟠 Avec des signes clairs de lutte, ce têtard a survécu contre toute attente."
            ]),
            ("worn", vec![
                "🟡 Ce têtard a navigué à travers de nombreux périls, un vrai petit guerrier des eaux.",
                "🟡 Portant les marques d'une vie déjà mouvementée, ce têtard montre des signes d'usure mais aussi de résilience.",
                "🟡 Un combattant des ruisseaux, ce têtard a une histoire à raconter avec chaque cicatrice."
            ]),
            ("good", vec![
                "🟢 Ce têtard est vif et alerte, prêt à sauter vers l'aventure.",
                "🟢 Avec une énergie débordante, ce têtard est un modèle de vitalité.",
                "🟢 Plein de vie et d'espoir, ce têtard a tout ce qu'il faut pour grandir en une belle grenouille."
            ]),
            ("pristine", vec![
                "✨ Un spécimen exceptionnel, ce têtard est l'image même de la perfection aquatique.",
                "✨ Impeccable et prometteur, ce têtard est sur la voie rapide pour devenir une grenouille remarquable.",
                "✨ Dans son état idéal, ce têtard est prêt à évoluer avec toutes les chances de son côté."
            ]),
        ]),
    ]);

    // UNCOMMON
    data.insert(Rarity::Uncommon, vec![
        fish_simple("Poisson Rouge", 0.5, 30.0, 15.0, vec![
            ("badly damaged", "🔴 Ses écailles sont ternes et abîmées, il a clairement vécu des moments difficiles."),
            ("damaged", "🟠 Il a quelques blessures superficielles mais reste reconnaissable."),
            ("worn", "🟡 Un poisson assez ordinaire avec quelques marques d'usure."),
            ("good", "🟢 Il est en bon état, avec des couleurs plutôt vives."),
            ("pristine", "✨ Un magnifique spécimen, parfaitement sain et éclatant de couleurs."),
        ]),
        fish_simple("Truite Arc-en-Ciel", 5.0, 60.0, 50.0, vec![
            ("badly damaged", "🔴 Ses nageoires sont abîmées et ses couleurs ont perdu leur éclat."),
            ("damaged", "🟠 Une belle truite, malgré quelques marques de lutte."),
            ("worn", "🟡 Elle est en bon état mais pas exceptionnelle."),
            ("good", "🟢 Ses écailles brillent avec des reflets arc-en-ciel."),
            ("pristine", "✨ Une truite parfaite, digne d'un trophée de pêche."),
        ]),
        fish_simple("Dorade Grise", 25.0, 40.0, 7.0, vec![
            ("badly damaged", "🔴 Une dorade malmenée, mais encore identifiable."),
            ("damaged", "🟠 Elle montre quelques cicatrices mais reste impressionnante."),
            ("worn", "🟡 Une belle prise, même si elle n'est pas parfaite."),
            ("good", "🟢 Une dorade élégante avec des reflets métalliques."),
            ("pristine", "✨ Une dorade grise de concours, immaculée et brillante."),
        ]),
        fish_simple("Tanche", 20.0, 40.0, 8.0, vec![
            ("badly damaged", "🔴 Une tanche abîmée, sa peau semble avoir subi de nombreuses épreuves."),
            ("damaged", "🟠 Un poisson robuste mais avec des cicatrices évidentes."),
            ("worn", "🟡 Une tanche solide, mais sans éclat particulier."),
            ("good", "🟢 Une belle tanche avec une peau luisante."),
            ("pristine", "✨ Une tanche magnifique, parfaitement intacte et brillante."),
        ]),
        fish_simple("Tilapia", 10.0, 25.0, 5.0, vec![
            ("badly damaged", "🔴 Un tilapia malmené, probablement attaqué par d'autres poissons."),
            ("damaged", "🟠 Il a subi des coups, mais reste mangeable."),
            ("worn", "🟡 Un tilapia en état moyen, mais toujours vigoureux."),
            ("good", "🟢 Un poisson en bonne santé, prêt pour une belle recette."),
            ("pristine", "✨ Un tilapia parfait, aux écailles éclatantes et bien proportionné."),
        ]),
        fish_simple("Vandoise", 15.0, 30.0, 6.0, vec![
            ("badly damaged", "🔴 Ce poisson semble avoir eu une vie difficile, ses écailles sont ternies."),
            ("damaged", "🟠 Une vandoise avec des marques de lutte, mais encore vive."),
            ("worn", "🟡 Un poisson correct, sans grande particularité."),
            ("good", "🟢 Une belle vandoise, en bonne condition."),
            ("pristine", "✨ Une vandoise éclatante, parfaite pour une photo."),
        ]),
        fish_simple("Calmar", 15.0, 25.0, 5.0, vec![
            ("badly damaged", "🔴 Un calmar avec des tentacules déchirés, il a vu des jours meilleurs."),
            ("damaged", "🟠 Ce calmar montre des marques de lutte, mais reste impressionnant."),
            ("worn", "🟡 Un calmar ordinaire, avec quelques blessures."),
            ("good", "🟢 Un calmar en pleine forme, ses tentacules brillent."),
            ("pristine", "✨ Un calmar parfait, une véritable beauté marine."),
        ]),
        fish_simple("Barbeau", 30.0, 50.0, 10.0, vec![
            ("badly damaged", "🔴 Ce barbeau est marqué par les eaux tumultueuses où il vit."),
            ("damaged", "🟠 Il a quelques éraflures, mais reste robuste."),
            ("worn", "🟡 Un barbeau solide, prêt à être pêché."),
            ("good", "🟢 Un superbe barbeau, brillant et vigoureux."),
            ("pristine", "✨ Une prise parfaite, un barbeau digne des trophées."),
        ]),
        fish_simple("Bouvière", 5.0, 12.0, 2.0, vec![
            ("badly damaged", "🔴 Cette petite bouvière est abîmée, mais toujours reconnaissable."),
            ("damaged", "🟠 Une bouvière avec des marques, mais encore vive."),
            ("worn", "🟡 Un poisson modeste, mais en bon état."),
            ("good", "🟢 Une belle bouvière, parfaite pour une prise en rivière."),
            ("pristine", "✨ Une bouvière éclatante, petite mais impressionnante."),
        ]),
        fish("Grenouille", 5.0, 10.0, 2.0, vec![
            ("badly damaged", vec![
                "🔴 Wat ze FOK is this ?? C'est vraiment une Grenouille ce machin là ??? ",
                "🔴 On ne pourrait même pas espérer cuisiner un truc pareil. Pauvre Grenouille.",
                "🔴 Cette grenouille a l'air d'avoir été écrasée par un camion poubelle.",
            ]),
            ("damaged", vec!["🟠 Une grenouille cabossée, probablement échappée d'une lutte."]),
            ("worn", vec!["🟡 Une grenouille ordinaire, avec des marques d'usure."]),
            ("good", vec!["🟢 Une grenouille en bonne santé, prête à bondir."]),
            ("pristine", vec![
                "✨🐸 Wow ! Quelle Grenouille remarquable ! Elle pourrait être servit telle quelle en sashimi 😱 !",
                "✨🐸 Prête pour le tapis rouge, cette grenouille pourrait être la vedette d'une soirée gastronomique de luxe.",
                "✨🐸 Tellement parfaite, elle pourrait être l'invitée d'honneur à un banquet de grenouilles.",
                "✨🐸 Une grenouille parfaite, avec une peau lisse et brillante.",
                "✨🐸 Non mais OH !! Poussez vous là, Monsieur Grenouille est dans la place !! Regardez moi cette prestance non dé diou ! Elle est sublime 🥰",
            ]),
        ]),
    ]);

    // RARE
    data.insert(Rarity::Rare, vec![
        fish_simple("Esturgeon Royal", 100.0, 200.0, 40.0, vec![
            ("badly damaged", "🔴 Un géant marqué par le temps, ses blessures racontent une histoire."),
            ("damaged", "🟠 Un grand poisson avec des éraflures, mais toujours imposant."),
            ("worn", "🟡 Il est robuste, même si les années se font sentir."),
            ("good", "🟢 Un esturgeon imposant et élégant."),
            ("pristine", "✨ Une prise légendaire, parfaitement préservée."),
        ]),
        fish("Thon Rouge", 80.0, 150.0, 30.0, vec![
            ("badly damaged", vec![
                "🔴 Un thon massif mais marqué par les filets de pêche.",
                "🔴 Immonde...... ah mais c'est un Thon Rouge ?? On dirait toi au réveil.",
                "🔴 Berk ! Ce thon Rouge a pris tellement de dégats qu'on dirait qu'il sort d'un 1V1 contre Darius 🤮 !",
                "🔴 Ca un Thon Rouge ??? On dirait un Fizz en 0/10/1 qui vient de manger un baril de gangplank !",
            ]),
            ("damaged", vec!["🟠 Il a quelques cicatrices mais reste impressionnant."]),
            ("worn", vec!["🟡 Un spécimen robuste et en bon état."]),
            ("good", vec!["🟢 Un thon rouge éclatant de santé."]),
            ("pristine", vec!["✨ Un thon majestueux, sans une égratignure."]),
        ]),
        fish("Saumon Atlantique", 60.0, 120.0, 25.0, vec![
            ("badly damaged", vec![
                "🔴 Un Saumon Atlantique ça ??? On dirait Fizz en 0/18/2 qui int midlane sur League of Legends c'est pas possible.... pauvre bête.",
                "🔴 Et beh !! Si ça c'est un Saumon d'Atlantique, je passe mon chemin. On dirait Borne après un 49.3 !",
                "🔴 Un Saumon d'Atlantique qui a pris tariff dans une rixe entre poiskaille !!",
                "🔴 C'est quoi ça ? Difficile à dire. C'est un Saumon d'Atlantique d'après les analyses ADN. On dirait plutôt ta belle mère menfin bon.",
            ]),
            ("damaged", vec!["🟠 Un poisson impressionnant, malgré des marques de lutte."]),
            ("worn", vec!["🟡 Un saumon robuste mais marqué par le voyage."]),
            ("good", vec!["🟢 Un saumon en pleine forme, prêt à frayer."]),
            ("pristine", vec!["✨ Un saumon parfait, symbole de puissance et de grâce."]),
        ]),
        fish_simple("Espadon", 200.0, 300.0, 50.0, vec![
            ("badly damaged", "🔴 Son épée est brisée, témoin d'innombrables batailles."),
            ("damaged", "🟠 Un espadon impressionnant, malgré quelques égratignures."),
            ("worn", "🟡 Un géant des mers, robuste mais marqué par le temps."),
            ("good", "🟢 Un espadon éclatant, symbole de puissance marine."),
            ("pristine", "✨ Une prise de légende, immaculée et majestueuse."),
        ]),
    ]);

    // VERY RARE
    data.insert(Rarity::VeryRare, vec![
        fish_simple("Piranha", 10.0, 20.0, 5.0, vec![
            ("badly damaged", "🔴 Un piranha avec des dents cassées, mais toujours menaçant."),
            ("damaged", "🟠 Un prédateur redoutable, même avec quelques cicatrices."),
            ("worn", "🟡 Un piranha robuste, mais sans grande particularité."),
            ("good", "🟢 Un piranha en pleine santé, prêt à mordre."),
            ("pristine", "✨ Un piranha parfait, une véritable machine à tuer."),
        ]),
        fish_simple("Poisson-Lune", 50.0, 150.0, 30.0, vec![
            ("badly damaged", "🔴 Un énorme poisson avec des blessures profondes, probablement des prédateurs."),
            ("damaged", "🟠 Un poisson-lune impressionnant mais marqué par ses aventures."),
            ("worn", "🟡 Une créature massive, un peu usée par les courants."),
            ("good", "🟢 Un poisson-lune en bon état, majestueux et étrange."),
            ("pristine", "✨ Un poisson-lune immaculé, sa forme étrange et parfaite fascine."),
        ]),
        fish_simple("Anguille Électrique", 30.0, 80.0, 15.0, vec![
            ("badly damaged", "🔴 Une anguille qui semble avoir perdu une partie de sa puissance électrique."),
            ("damaged", "🟠 Une anguille redoutable, bien que légèrement affaiblie."),
            ("worn", "🟡 Une anguille vigoureuse mais pas à son plein potentiel."),
            ("good", "🟢 Une anguille électrique en pleine forme, ses décharges sont impressionnantes."),
            ("pristine", "✨ Une anguille parfaite, symbole de danger et de puissance."),
        ]),
    ]);

    // EPIC
    data.insert(Rarity::Epic, vec![
        fish_simple("Poisson-Clown", 5.0, 12.0, 2.0, vec![
            ("badly damaged", "🔴 Ses couleurs sont ternes et ses nageoires abîmées, mais il reste identifiable."),
            ("damaged", "🟠 Un poisson-clown encore vif mais avec des écailles abîmées."),
            ("worn", "🟡 Un poisson-clown mignon, mais marqué par la vie."),
            ("good", "🟢 Un poisson-clown éclatant, parfait pour un aquarium."),
            ("pristine", "✨ Un poisson-clown magnifique, aux couleurs vives et parfaites."),
        ]),
        fish("Coelacanthe", 100.0, 180.0, 20.0, vec![
            ("badly damaged", vec!["🔴 Un fossile vivant, abîmé par le temps mais toujours fascinant."]),
            ("damaged", vec!["🟠 Un coelacanthe imposant, malgré ses blessures évidentes."]),
            ("worn", vec!["🟡 Une créature rare et robuste, témoin d'un temps révolu."]),
            ("good", vec!["🟢 Un coelacanthe en excellent état, un véritable trésor préhistorique."]),
            ("pristine", vec![
                "✨ Une découverte parfaite : un Cœlacanthe immaculé et impressionnant.",
                "✨ Wow ! Ce Cœlacanthe est dans un parfait état ! Ca se mange vous pensez ?",
                "✨ Par bélénosse !! Ce Cœlacanthe est tellement parfait !! On dirait @KiketteBot 😂 !!",
                "✨ Ce Cœlacanthe est impeccable, un fossile vivant redécouvert in 1938 après avoir été considéré éteint pendant des millions d'années.",
                "✨ Un Cœlacanthe impeccable, un 'fossile vivant' qui échappe à l'extinction depuis le Jurassique.",
                "✨ Ce Cœlacanthe est parfait, un survivant des âges préhistoriques découvert vivant en 1938.",
                "✨ Impeccable Cœlacanthe, un poisson que le temps a oublié, mais que la mer a conservé."
            ]),
        ]),
        fish("Requin Marteau", 500.0, 3500.0, 500.0, vec![
            ("badly damaged", vec![
                "🔴 Un requin martelé par les vagues et les combats, mais toujours terrifiant.",
                "🔴 Ce requin-marteau a vu des jours meilleurs; même avec sa vision à 360 degrés, il n'a pas pu esquiver le dernier coup.",
                "🔴 Malgré ses capacités à détecter les champs électriques, ce requin-marteau porte les stigmates de batailles sous-marines acharnées.",
                "🔴 Battu par les vagues et marqué par les prédateurs, ce requin a toujours sa tête emblématique, bien qu'amochée.",
                "🔴 Ce requin-marteau, autrefois maître des détours rapides, semble avoir eu un parcours difficile dans les fonds marins.",
                "🔴 Même avec sa capacité unique à balayer les sables océaniques, ce requin-marteau porte les cicatrices d'un dur voyage."
            ]),
            ("damaged", vec!["🟠 Un requin-marteau redoutable, malgré des cicatrices évidentes."]),
            ("worn", vec!["🟡 Une force des océans, légèrement usée par le temps."]),
            ("good", vec!["🟢 Un requin-marteau imposant et en pleine santé."]),
            ("pristine", vec![
                "✨ Un requin-marteau parfait, une légende des profondeurs.",
                "✨ Ce requin-marteau est impeccable, célèbre pour sa tête en forme de T qui améliore son radar sensoriel.",
                "✨ Parfaitement préservé, ce requin-marteau utilise sa tête large pour mieux détecter ses proies.",
                "✨ Un spécimen éblouissant, ce requin-marteau montre pourquoi sa silhouette unique est un avantage évolutif.",
                "✨ Impeccable et majestueux, ce requin-marteau représente l'apex de l'adaptation marine.",
                "✨ Ce requin-marteau en état pristine démontre l'évolution parfaite pour la chasse sous-marine.",
                "✨ Impeccable requin-marteau, doté d'une vision à 360 degrés grâce à la position unique de ses yeux."
            ]),
        ]),
    ]);

    // LEGENDARY
    data.insert(Rarity::Legendary, vec![
        fish_forced("Pristine Banana 1", 5.0, 10.0, 1.0, vec![
            ("pristine", "✨😱 Wow !! It is the ✨Pristine✨ Banana 1 🍌 !! A rare treasure for the Banana Lovers !!")
        ]),
        fish_forced("Pristine Banana 2", 5.0, 10.0, 2.0, vec![
            ("pristine", "✨😱 Wow !! It is the ✨Pristine✨ Banana 2 🍌 !! A rare treasure for the Banana Lovers !!")
        ]),
    ]);

    // MYTHICAL
    data.insert(Rarity::Mythical, vec![
        fish_forced("Carte Postale", 0.0, 12.0, 0.5, vec![
            ("pristine", "✨😱 Woooww !!! This is the only one ✨Pristine✨ Postcard signed \"MonsieurCotCot\" ! Awesome treasure.")
        ]),
    ]);

    data
}

// Helpers to reduce boilerplate
fn fish(name: &str, min: f64, mean: f64, sigma: f64, descs: Vec<(&str, Vec<&str>)>) -> FishData {
    FishData {
        name: name.to_string(),
        size_min: min,
        size_mean: mean,
        size_sigma: sigma,
        force_pristine: None,
        descriptions: descs.into_iter().map(|(k, v)| (k.to_string(), v.into_iter().map(|s| s.to_string()).collect())).collect(),
    }
}

fn fish_simple(name: &str, min: f64, mean: f64, sigma: f64, descs: Vec<(&str, &str)>) -> FishData {
    FishData {
        name: name.to_string(),
        size_min: min,
        size_mean: mean,
        size_sigma: sigma,
        force_pristine: None,
        descriptions: descs.into_iter().map(|(k, v)| (k.to_string(), vec![v.to_string()])).collect(),
    }
}

fn fish_forced(name: &str, min: f64, mean: f64, sigma: f64, descs: Vec<(&str, &str)>) -> FishData {
    FishData {
        name: name.to_string(),
        size_min: min,
        size_mean: mean,
        size_sigma: sigma,
        force_pristine: Some(true),
        descriptions: descs.into_iter().map(|(k, v)| (k.to_string(), vec![v.to_string()])).collect(),
    }
}
